### ISSUE TITLE
Product Features missing

### ISSUE THREAD

**Issue by massmagic85** [clerkio/clerk-prestashop#13]
Good evening,
I have installed on my prestashop 1.7.8.6 last version of your module 6.6.0
I need to include all product feature for boost some products and I have enabled in the module configuration the option "Include Product Features"
After the full sync with clerk.io seems that no features is included.

I tried to disable "Include Product Features" and start a new sync with clerk.io and all feature are present but time by time almost every product lose all the prestashop features previously included. If i restart the sync manually all features are coming back on clerk.io but after some time features are not present again..

Can you check if this functionality is fully working in 6.6.0 and not bugged?
Thank you

**Comment by stubbedev** [comment]
Hi Massmagic,

I have added the product features to the realtime updates, as this was the cause for the features dissapearing piecemeal throughout a day.

https://github.com/clerkio/clerk-prestashop/commit/77c72f07e22fc2f258baaa9cf14244dee8aea596
