### ISSUE TITLE
Module compatibility with Prestashop 8

### ISSUE THREAD

**Issue by Oksydan** [clerkio/clerk-prestashop#22]
Module ins't compatible with Prestashop 8.X.

Module is using `Attribute` class instead of `ProductAttribute`. 
Since php 8 `Attribute` is reserved word. To make this module compatible with Prestashop 8.X this code have to adjusted with backwards compatibility for Prestashop < 8.

**Comment by stubbedev** [comment]
Hey there,

Thanks for letting me know Oksydan. I believe this commit should address the issue.

https://github.com/clerkio/clerk-prestashop/commit/41edb1255e6a81198bdff7638af7515e7f6be83e
