### ISSUE TITLE
Issue with php versions

### ISSUE THREAD

**Issue by Prestaworks** [clerkio/clerk-prestashop#4]
The code is not working on php 5.4

change
$this->shop_id = (! empty(Tools::getValue('clerk_shop_select'))) ? (int)Tools::getValue('clerk_shop_select') : $this->context->shop->id;

to 
$this->shop_id = Tools::getIsset('clerk_shop_select') ? (int)Tools::getValue('clerk_shop_select') : $this->context->shop->id;

$this->language_id = (! empty(Tools::getValue('clerk_language_select'))) ? (int)Tools::getValue('clerk_language_select') : $this->context->language->id;

to
$this->language_id = Tools::getIsset('clerk_language_select') ? (int)Tools::getValue('clerk_language_select') : $this->context->language->id;

And

if (! empty(Tools::getValue('ignore_changes'))) {
                return true;
            }

to
if (Tools::getIsset('ignore_changes')) {
                return true;
            }

**Comment by Prestaworks** [comment]
Last one shoul be changed to

if ("" != Tools::getValue('ignore_changes')) {
                return true;
            }
since it seems to be included even when saving settings

**Comment by RBech** [comment]
Sorry for the very late response, we'll likely implement the changes but PHP 5.4 had end of life in september 2015 and as such we wont be taking this version into consideration in future releases, currently we're supporting the same versions as listed here http://php.net/supported-versions.php
